// examples/frontend/vue/src/Chat.vue
<script setup lang="ts">
import { ref } from "vue";
import { useAgentChat } from "@camelai/agent-runtime-vue";

// Demo sign-in: a random user per browser (see server.ts).
const user = (localStorage.demoUser ??= crypto.randomUUID());
const { messages, status, send, stop } = useAgentChat({ endpoint: "/api/agent", headers: { "x-demo-user": user } });
const text = ref("");
const submit = () => { if (text.value.trim()) void send(text.value); text.value = ""; };
</script>

<template>
  <main style="max-width: 640px; margin: 0 auto; padding: 16px">
    <div v-for="message in messages" :key="message.id" :data-role="message.role" style="margin: 8px 0; white-space: pre-wrap">
      <b>{{ message.role === "user" ? "You" : "Agent" }}:</b>
      <template v-if="message.role === 'user'">{{ message.text }}</template>
      <template v-else v-for="part in message.parts" :key="part.id">
        <span v-if="part.type === 'text'">{{ part.text }}</span>
        <i v-else-if="part.type === 'tool'"> [{{ part.name }}: {{ part.state }}] </i>
      </template>
    </div>
    <form @submit.prevent="submit" style="display: flex; gap: 8px">
      <input v-model="text" aria-label="Message" placeholder="Message the agent…" style="flex: 1" />
      <button v-if="status === 'streaming' || status === 'submitted'" type="button" @click="stop()">Stop</button>
      <button v-else>Send</button>
    </form>
  </main>
</template>

// examples/frontend/svelte/src/Chat.svelte
<script lang="ts">
  import { agentChat } from "@camelai/agent-runtime-svelte";

  // Demo sign-in: a random user per browser (see server.ts).
  const user = (localStorage.demoUser ??= crypto.randomUUID());
  const { messages, status, send, stop } = agentChat({ endpoint: "/api/agent", headers: { "x-demo-user": user } });
  let text = $state("");
  const submit = (event: SubmitEvent) => { event.preventDefault(); if (text.trim()) void send(text); text = ""; };
</script>

<main style="max-width: 640px; margin: 0 auto; padding: 16px">
  {#each $messages as message (message.id)}
    <div data-role={message.role} style="margin: 8px 0; white-space: pre-wrap">
      <b>{message.role === "user" ? "You" : "Agent"}:</b>
      {#if message.role === "user"}{message.text}
      {:else}{#each message.parts as part (part.id)}{#if part.type === "text"}{part.text}{:else if part.type === "tool"}<i> [{part.name}: {part.state}] </i>{/if}{/each}{/if}
    </div>
  {/each}
  <form onsubmit={submit} style="display: flex; gap: 8px">
    <input bind:value={text} aria-label="Message" placeholder="Message the agent…" style="flex: 1" />
    {#if $status === "streaming" || $status === "submitted"}<button type="button" onclick={() => stop()}>Stop</button>{:else}<button>Send</button>{/if}
  </form>
</main>
