// examples/frontend/solid/src/main.tsx
import { For, Show, createSignal } from "solid-js";
import { render } from "solid-js/web";
import { useAgentChat } from "@camelai/run-solid";

// Demo sign-in: a random user per browser (see server.ts).
const user = (localStorage.demoUser ??= crypto.randomUUID());

function Chat() {
  const chat = useAgentChat({ endpoint: "/api/agent", headers: { "x-demo-user": user } });
  const [text, setText] = createSignal("");
  const busy = () => chat.status() === "streaming" || chat.status() === "submitted";
  return (
    <main style={{ "max-width": "640px", margin: "0 auto", padding: "16px" }}>
      <For each={chat.messages()}>{message => (
        <div data-role={message.role} style={{ margin: "8px 0", "white-space": "pre-wrap" }}>
          <b>{message.role === "user" ? "You" : "Agent"}:</b>{" "}
          {message.role === "user" ? message.text : <For each={message.parts}>{part =>
            part.type === "text" ? part.text : part.type === "tool" ? <i> [{part.name}: {part.state}] </i> : null}</For>}
        </div>
      )}</For>
      <form style={{ display: "flex", gap: "8px" }} onSubmit={event => { event.preventDefault(); if (text().trim()) void chat.send(text()); setText(""); }}>
        <input value={text()} onInput={event => setText(event.currentTarget.value)} aria-label="Message" placeholder="Message the agent…" style={{ flex: 1 }} />
        <Show when={busy()} fallback={<button>Send</button>}><button type="button" onClick={() => chat.stop()}>Stop</button></Show>
      </form>
    </main>
  );
}

render(() => <Chat />, document.getElementById("app")!);

// examples/frontend/ai-sdk/src/main.tsx
import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { useChat } from "@ai-sdk/react";
import { AgentRuntimeChatTransport } from "@camelai/run/ai-sdk";

// Demo sign-in: a random user per browser (see server.ts).
const user = localStorage.demoUser ??= crypto.randomUUID();
const transport = new AgentRuntimeChatTransport({ endpoint: "/api/agent", headers: { "x-demo-user": user } });

function Chat() {
  // The chat's id is the route's thread: the agent keeps the conversation.
  const { messages, setMessages, sendMessage, status, stop } = useChat({ id: "main", transport });
  useEffect(() => { void transport.loadMessages({ chatId: "main" }).then(history => setMessages(history as never)); }, [setMessages]);
  const [text, setText] = useState("");
  return (
    <main style={{ maxWidth: 640, margin: "0 auto", padding: 16, font: "15px/1.5 system-ui, sans-serif" }}>
      {messages.map(message => (
        <div key={message.id} data-role={message.role} style={{ margin: "8px 0", whiteSpace: "pre-wrap" }}>
          <b>{message.role === "user" ? "You" : "Agent"}:</b>{" "}
          {message.parts.map((part, at) => part.type === "text" ? <span key={at}>{part.text}</span>
            : part.type === "dynamic-tool" ? <i key={at}> [{part.toolName}: {part.state}] </i> : null)}
        </div>
      ))}
      <form style={{ display: "flex", gap: 8 }} onSubmit={event => { event.preventDefault(); if (text.trim()) void sendMessage({ text }); setText(""); }}>
        <input value={text} onChange={event => setText(event.target.value)} aria-label="Message" placeholder="Message the agent…" style={{ flex: 1 }} />
        {status === "streaming" || status === "submitted" ? <button type="button" onClick={() => void stop()}>Stop</button> : <button>Send</button>}
      </form>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(<Chat />);
